name: Deployment CI

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy Server
    runs-on: ubuntu-latest

    steps:
      - name: 🛎️ Checkout Repository
        uses: actions/checkout@v4

      - name: 🛡️ Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.SSH_SECRET }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: 🔐 Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 🐳 Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 🏗️ Build and push Container image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.revision=${{ github.sha }}
          outputs: type=docker,dest=/tmp/lncrawl.tar
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: 📦 Transfer Docker Image
        run: |
          gzip < /tmp/lncrawl.tar | ssh "${{ secrets.DEPLOY_SERVER }}" 'gunzip | docker load'

      - name: 📤 Upload Compose File
        run: |
          scp ./scripts/server-compose.yml "${{ secrets.DEPLOY_SERVER }}:~/lncrawl/compose.yml"

      - name: 🚀 Deploy over SSH
        run: |
          ssh "${{ secrets.DEPLOY_SERVER }}" << 'EOF'
            mkdir -p ~/lncrawl/output_path
            cd ~/lncrawl
            touch .env
            chown 1000:1000 .env output_path
            docker compose -f ~/lncrawl/compose.yml up -d
          EOF
